name: Build and Deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.12.2'
        cabal-version: '3.14.2.0'
    - name: Cache .cabal
      uses: actions/cache@v4.2.3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.local/state/cabal/store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build Server
      run: cabal update && cabal build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: server-bin
        path: ./dist-newstyle/build/x86_64-linux/ghc-9.12.2/t-sasaki-net-server-0.1.0.0/x/t-sasaki-net-server/build/t-sasaki-net-server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{secrets.SSH_PORT}} -H ${{secrets.SSH_HOST}} > ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: server-bin
    - name: Deploy server
      run: scp $GITHUB_WORKSPACE/t-sasaki-net-server -p ${{secrets.SSH_PORT}} -i ~/.ssh/id_rsa ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:~/
      
